<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto

namespace GPBMetadata;

class Users
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0acc010a0b75736572732e70726f746f12057573657273221b0a0b557365" .
            "7252657175657374120c0a046e616d6518012001280922440a0c55736572" .
            "526573706f6e7365120a0a026964180120012805120c0a046e616d651802" .
            "20012809120b0a03616765180320012805120d0a057469746c6518042003" .
            "2809324b0a0f55736572496e666f5365727669636512380a0b4765745573" .
            "6572496e666f12122e75736572732e55736572526571756573741a132e75" .
            "736572732e55736572526573706f6e73652200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

